### PR TITLE
throw error if file not found

### PR DESCRIPTION
**Pull request by pweigmann**
`getSystemFile` currently does not throw an error if a file is not found in develop-mode

### CODE REVIEW

**Review by robinhasse — COMMENTED** [review]
I personally would not add this feature by default as I understand this function as a wrapper of `system.file` that allows it to work with development packages and this check is not done there either, right? But I don't have very strong feelings about that and could live with this check also. I actually implemented it myself in [BRICK](https://github.com/pik-piam/brick/blob/887737d8048b204247d60392f64895b2fd7f670f/R/brick.file.R#L19-L21).

**Comment by pweigmann** [comment]
> I personally would not add this feature by default as I understand this function as a wrapper of `system.file` that allows it to work with development packages and this check is not done there either, right? But I don't have very strong feelings about that and could live with this check also. I actually implemented it myself in [BRICK](https://github.com/pik-piam/brick/blob/887737d8048b204247d60392f64895b2fd7f670f/R/brick.file.R#L19-L21).

So ``base::system.file(package = package, mustWork = TRUE)`` does throw an error if the file is not found, but in the current formulation ``file.path(base::system.file(package = package, mustWork = TRUE), "inst", files)`` does not throw an error as ``system.file`` only looks for the package path and not for the file. The ``mustWork`` looks to me like I would expect to get an error.

`devtools::load_all()`
`getSystemFile("thisFileDoesNotExist", package = "thisPackageDoesExist")`

returns a path to the non existing file at the moment.

**Comment by fbenke-pik** [comment]
If `base::system.file` crashes, this wrapper should, too.

**Review by fbenke-pik — APPROVED** [review]

**Comment by robinhasse** [comment]
How about this rewrite? It should behave just like `base::system.file` but also work with dev packages. Mind that you can now pass file paths with multiple arguments using `...` just like with the original.
```R
getSystemFile <- function(..., package = "base", mustWork = FALSE) {
  fileNames <- if (is_dev_package(package)) {
    file.path(base::system.file(package = package), "inst", ...)
  } else {
    system.file(..., package = package)
  }
  if (!file.exists(fileNames)) {
    if (mustWork) {
      stop("no file found")
    } else {
      return("")
    }
  }
  return(fileNames)
}
```

**Comment by pweigmann** [comment]
> How about this rewrite? It should behave just like `base::system.file` but also work with dev packages. Mind that you can now pass file paths with multiple arguments using `...` just like with the original.
> 
> ```r
> getSystemFile <- function(..., package = "base", mustWork = FALSE) {
>   fileNames <- if (is_dev_package(package)) {
>     file.path(base::system.file(package = package), "inst", ...)
>   } else {
>     system.file(..., package = package)
>   }
>   if (!file.exists(fileNames)) {
>     if (mustWork) {
>       stop("no file found")
>     } else {
>       return("")
>     }
>   }
>   return(fileNames)
> }
> ```

Looks good to me! I will set up another PR.

**Pull request merged**
